### ISSUE TITLE
[BUG] response_model_skip_defaults doesn't work when response is a list of models

### ISSUE THREAD

**Issue by draklaw** [tiangolo/fastapi#675] opened 2019-11-02 20:31 UTC
**Describe the bug**
This is a followup of bug #421. When an endpoint returns a list of Pydantic models with `response_model_skip_defaults = True`, the resulting json contains the fields with default values. It should not.

**To Reproduce**
Here is the minimal failing test case of bug #421, slightly updated to return a list of models instead of a model:

```py
from typing import List, Optional

from fastapi import FastAPI
from pydantic import BaseModel
from starlette.testclient import TestClient


def test_return_defaults():
    app = FastAPI()

    class Model(BaseModel):
        x: Optional[int]

    @app.get("/", response_model=List[Model], response_model_skip_defaults=True)
    def get_x() -> Model:
        return [Model()]  # adding `.dict(skip_defaults=True)` causes the test to pass

    assert TestClient(app).get("/").content == b"[{}]"
    # Fail: b'{"x":null}' != b'[{}]'
```

**Expected behavior**
The resulting json should not contain the default values.

**Environment:**
 - OS: Linux
 - FastAPI 0.42.0
 - Python 3.7.3

**Comment by dmontagu** [comment] 2019-11-02 21:46
The source of the problem is this line:
https://github.com/tiangolo/fastapi/blob/65536cbf63318d111bf608960378d651b6c1596a/fastapi/routing.py#L48

Ultimately, the reason this is hard to handle well has to do with what happens when the model is parsed into the secure cloned field. With the current infrastructure, I think it would be relatively hard to handle all possible edge cases properly. (See below for my proposed approach to address the infrastructure issue.)

I think there are basically two workarounds currently:
1. Wrap your response inside a pydantic model with a top level key containing the list. If you do that, skip defaults should work appropriately.
2. If you can't do that for some reason (e.g., need to maintain backwards compatibility with an API that returns a top-level list), you should just manually call the `.dict(skip_defaults=True)` prior to returning the response, as you noted in your test.

------

I have an in-progress pydantic PR that should remove the need for the secure cloned field (https://github.com/samuelcolvin/pydantic/pull/812 -- it is only closed because I'm in the process of breaking it up into multiple PRs); once fastapi supports pydantic v1 this is my next highest priority -- it appears to speed up fastapi's serialization by up to ~3x (if you specify a response model, anyway).

With that functionality built into pydantic, it would become trivial to implement proper handling of `response_model_skip_defaults`.

**Comment by draklaw** [comment] 2019-11-02 22:10
Yes, I guessed that fixing this properly would be a bit messy with the current implementation. I've switched to using `.dict(skip_defaults=True)`, which is not an issue in my case. Still I submitted the bug for the records.

Thanks for the feedback.

**Comment by dmontagu** [comment] 2019-11-02 22:13
Much appreciated! Hopefully we can fix it soon.

**Comment by hellocoldworld** [comment] 2021-02-17 17:00
I can still reproduce this with fastapi==0.63

**Comment by tiangolo** [comment] 2022-11-11 11:05
Thanks for the help here everyone! 👏  🙇 

If that solves the original problem, then you can close this issue ✔️

This will probably improve soon once we have Pydantic v2 and it's integrated into FastAPI. 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Closed** 2022-11-22 00:17 UTC
Labels: bug, answered
