### ISSUE TITLE
[FEATURE] Support for Headers/Path/Query on websocket routes

### ISSUE THREAD

**Issue by jekirl** [tiangolo/fastapi#166] opened 2019-04-19 04:36 UTC
**Is your feature request related to a problem? Please describe.**
I want to be able to use `Header` and other dependencies in a websocket route

**Describe the solution you'd like**
The ability to do this:
```python
@app.websocket_route("/ws")
async def websocket_endpoint(websocket: WebSocket, user_tag: str = Header(None),
    assert user_tag == "foo"
    await websocket.accept()
        await websocket.send_text(f"user_tag: {user_tag}")

async with websockets.connect('ws://0.0.0.0:8000/ws', extra_headers={"User-Tag" "foo"}) as websocket:
    user_tag = await websocket.recv()
    assert user_tag == "user_tag: foo" 


```

**Describe alternatives you've considered**
One bad solution that poorly works without modifying fastapi is to trick `get_dependant` and resolve within function scope, this is obviously not ideal...
```python
@app.websocket_route("/ws")
async def websocket_endpoint(websocket: Request, user_tag: str = Header(None),
    websocket = typing.cast(websocket, WebSocket)
    dep = get_dependant(path="/ws", call=websocket_endpoint)
    values, errors, bg_tasks = await solve_dependencies(request=websocket, dependant=dep)
    assert values["user_tag"] == "foo"
```

A better solution would be to extend `websocket_route` and to adjust the conditional on `get_dependant` to 
```python
        elif lenient_issubclass(param.annotation, Request) or lenient_issubclass(param.annotation, WebSocket):
            dependant.request_param_name = param_name
```

If there already exists a solution for this, great! otherwise I could probably do a PR in the next few days

**Comment by tiangolo** [comment] 2019-04-19 06:27
I see, it's an interesting idea, but the problem is that it's not supported by browsers: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

**Comment by jekirl** [comment] 2019-04-19 22:33
Looks like browsers only support sending Cookies alongside a websocket connection -- still useful for auth I would assume. Our main use case is from iOS where we use starscream which has strong header support. Would you be open to accepting a PR?

**Comment by tiangolo** [comment] 2019-04-20 07:56
> Our main use case is from iOS where we use starscream which has strong header support

I get it, great.

> Would you be open to accepting a PR?

Yep, absolutely. :rocket:

**Comment by tiangolo** [comment] 2019-05-30 15:09
As the PR is already merged and released a couple of versions ago, I'll close this issue now. But feel free to add more comments or create new issues.

**Closed by tiangolo** 2019-05-30 15:09 UTC
Labels: enhancement
