### ISSUE TITLE
[BUG] Header duplicate on subdependency

### ISSUE THREAD

**Issue by henriklindgren** [tiangolo/fastapi#416] opened 2019-08-01 16:04 UTC
**Describe the bug**
Getting duplicate headers on API methods with subdependencies requiring the same dependency with a Header argument.

**To Reproduce**
I've created an example repo to reproduce https://github.com/henriklindgren/fastapi-header-bug
1. Create an API-method which uses the same dependency, with a Header argument, in each of 2 paths of the dependency tree. Like this https://github.com/henriklindgren/fastapi-header-bug/blob/master/app/main.py
2. Visit generated OpenApi json and see duplicate header requirements for the method. 
```json
"parameters": [
  {
    "required": true,
    "schema": {
      "title": "Someheader",
      "type": "string"
    },
    "name": "someheader",
    "in": "header"
  },
  {
    "required": true,
    "schema": {
      "title": "Someheader",
      "type": "string"
    },
    "name": "someheader",
    "in": "header"
  }
]
```

**Expected behavior**
A single header requirement shown in the OpenApi definition.

**Environment:**
 - OS: Linux
 - FastAPI Version: 0.33.0
 - Python Version: 3.7.3

**Comment by dmontagu** [comment] 2019-08-01 17:37
Here's a failing test case based on the provided repo:

```python
from starlette.testclient import TestClient

from fastapi import FastAPI, Header, Depends

app = FastAPI(title='Access', redoc_url=None)


def get_header(someheader: str = Header(...)):
    return someheader


def get_something_else(someheader: str = Depends(get_header)):
    return f'{someheader}123'


@app.get('/')
def get_deps(dep1: str = Depends(get_header), dep2: str = Depends(get_something_else)):
    return {'dep1': dep1, 'dep2': dep2}


client = TestClient(app)


def test_double_header():
    response = client.get("/openapi.json")
    assert response.status_code == 200
    parameters = response.json()['paths']['/']['get']['parameters']
    assert len(parameters) == 1, str(parameters)
```
Looking into whether it's a simple fix now...

**Comment by dmontagu** [comment] 2019-08-01 19:02
I figured out the source of the issue -- it's because during openapi spec generation, the raw flat_dependant is used, which includes duplicate dependencies (which are ignored or not based on the caching). However, I can't imagine a scenario where this distinction is relevant externally -- whether the dependency is cached or not, you can't provide distinct inputs for each repeated (uncached) call.

I created a PR (#417) that, when building the openapi schema, uses the caching logic to build a flat dependant that won't replicate dependencies that would have the same cache key. (It does not affect the generation of the flat dependant as it is used during actual route execution.)

**Comment by tiangolo** [comment] 2019-08-26 13:39
@henriklindgren thanks for reporting it!

Great job @dmontagu ! :open_mouth: :clap: :tada: Thanks for debugging and fixing it.

The fix is now available in FastAPI `0.36.0`.


---

I'll close this issue now, but feel free to add more comments or issues.

**Closed by tiangolo** 2019-08-26 13:39 UTC
Labels: bug

**Comment by dmig-alarstudios** [comment] 2020-05-19 07:43
Hey @tiangolo!
Unfortunately, this is not fixed :(

We've been facing this issue for a long time and just now decided to dig deeper to investigate.

Here is a testcase:
```python3
from fastapi import Depends, Response, FastAPI

app = FastAPI()

async def auth_header(response: Response):
    response.headers.setdefault('X-My-Header', 'test')
    response.headers['X-My-Other-Header'] = 'test'
    return response


async def empty_depends():
    return

@app.get('/')
async def main(
        updated_resp: Response = Depends(auth_header),
        # empty: None = Depends(empty_depends),
        empty1: None = Depends(empty_depends)
    ):
    return 'hello world'
```

every usage of `Depends()` in `main()` duplicates custom headers list:
```
$ curl -v "http://127.0.0.1:8000/" -H "accept: application/json"
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.68.0
> accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Tue, 19 May 2020 07:41:17 GMT
< server: uvicorn
< content-length: 13
< content-type: application/json
< x-my-header: test
< x-my-other-header: test
< x-my-header: test
< x-my-other-header: test
< 
* Connection #0 to host 127.0.0.1 left intact
"hello world"
```

Uncomment `empty` parameter to get this:
```
$ curl -v "http://127.0.0.1:8000/" -H "accept: application/json"
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.68.0
> accept: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Tue, 19 May 2020 07:42:30 GMT
< server: uvicorn
< content-length: 13
< content-type: application/json
< x-my-header: test
< x-my-other-header: test
< x-my-header: test
< x-my-other-header: test
< x-my-header: test
< x-my-other-header: test
< x-my-header: test
< x-my-other-header: test
< 
* Connection #0 to host 127.0.0.1 left intact
"hello world"
```

**Comment by dmig-alarstudios** [comment] 2020-05-19 10:20
I believe the bug is here:
https://github.com/tiangolo/fastapi/blob/master/fastapi/dependencies/utils.py#L481-L489

Not sure what would be the correct behavior:
- was it supposed to use individual `Response` instance for each dependency? Then the problem -- it's not being used.
- was it supposed that each dependency may modify existing `Response` instance? Then problem is caused by https://github.com/tiangolo/fastapi/blob/master/fastapi/dependencies/utils.py#L489

**Comment by dmig-alarstudios** [comment] 2020-05-19 15:04
I think the fix would be:
```diff
- response.headers.raw.extend(sub_response.headers.raw)
+ if response is not sub_response:
+   response.headers.raw.extend(sub_response.headers.raw)
```

**Comment by dmig-alarstudios** [comment] 2020-06-01 09:07
@tiangolo could you please have a look at this?

**Comment by peku33** [comment] 2022-04-04 18:59
Expirienced the same bug, is there any work ongoing?
