### ISSUE TITLE
Do FastAPI store a session/endpoints data/logic somewhere?

### ISSUE THREAD

**Issue by tarnopolskyi** [tiangolo/fastapi#2522] opened 2020-12-16 12:37 UTC
In short, my problem is this
I created an endpoint, then I commented out some of the code, and the logic continues to work.
Why it happens?

And how to fix this? Where problem can be?

-->

```Python
import os
import subprocess
from PIL import Image
from fastapi import FastAPI, status
from fastapi.responses import FileResponse

app = FastAPI()



@app.get('/file/')
async def get_file():
    print('here')
    screen_path = 'scrreen.png'

    command = f'ffmpeg -i mystream.m3u8 -ss 00:00:01 -vframes 1 {screen_path} -y'
    execute = subprocess.Popen([command], shell=True)
    print()
    print()
    print()
    print(dir(execute))
    print()
    print()
    print()
    print(execute.returncode)
    print()
    print()
    print()
    print()
    print()
    print()
```

Here was code for returning image and size of it. I've deleted it, but logic is the same still, even after reloading server

![image](https://user-images.githubusercontent.com/47281757/102349599-433e1900-3fac-11eb-9cd2-9bb13408dccc.png)

**Comment by Mause** [comment] 2020-12-16 12:44
Are you restarting your API between changes?

**Comment by tarnopolskyi** [comment] 2020-12-16 12:58
> Are you restarting your API between changes?

Yes. I have enabled reloading in uvicorn settings. And after restarting server is still the same

**Comment by Mause** [comment] 2020-12-16 13:02
Does your API actually restart when you make changes? IE, does it log that it is restarting?

**Comment by tarnopolskyi** [comment] 2020-12-16 13:05
> Does your API actually restart when you make changes? IE, does it log that it is restarting?

WARNING:  StatReload detected file change in 'app.py'. Reloading...
yes
i just got this message after changing file

**Comment by Mause** [comment] 2020-12-16 22:46
Well to answer your original question, fastapi does not cache or persist your code anywhere.

Perhaps if you are able to provide a replication of your issue we can find the cause?

**Comment by jhb** [comment] 2020-12-20 13:50
Maybe it is that your browser caches the file? So maybe headers to prevent caching are needed?

**Comment by tarnopolskyi** [comment] 2020-12-21 17:41
> Maybe it is that your browser caches the file? So maybe headers to prevent caching are needed?

good idea
but why it was happend only with this method. Everyone else works well

**Comment by tarnopolskyi** [comment] 2020-12-21 17:42
> Well to answer your original question, fastapi does not cache or persist your code anywhere.
> 
> Perhaps if you are able to provide a replication of your issue we can find the cause?

i can provide steps & code

**Comment by Mause** [comment] 2020-12-22 01:28
Please do

**Comment by tiangolo** [comment] 2022-11-09 21:20
Thanks for the help here everyone! 👏  🙇 

If you solved your problem @tarnopolskyi, then you can close this issue ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Closed** 2022-11-20 00:17 UTC
Labels: question, answered
