### ISSUE TITLE
Generate openapi schema without running server

### ISSUE THREAD

**Issue by BenDavidAaron** [tiangolo/fastapi#1490] opened 2020-05-27 21:21 UTC
### Is your feature request related to a problem

Not a bug, just a problem with my CI system.

I want to be able to programmatically access the openapi schema and save it to a file without running the web server

### The solution you would like

Ideally, I'd like to write a script that would output the openapi schema without running the webserver.

```
from myapp.api import api
json.dump(
  get_schema_from_app(api),
  open('openapi_schema.json', 'w')
)
```

### Describe alternatives you've considered

I've considered running the app in my CICD workflow and requesting the schema via http, but that seems like a lot of overhead, and I'd bet the functions to do what I want are already in the code and just need to be invoked in the right order. 

### Additional context

Nothing to add, other than I'm gonna open a PR and see if I can figure it out.

**Comment by phy25** [comment] 2020-05-27 22:10
Duplicate of #1173.

**Comment by BenDavidAaron** [comment] 2020-05-27 22:32
@phy25, thanks for the link, it was exactly what I needed. I'll close out.

**Comment by tiangolo** [comment] 2020-06-06 20:55
Thanks for the help here @phy25 ! :clap: :bow: 

Thanks for reporting back and closing the issue @BenDavidAaron  :+1:

**Closed** 2023-02-28 08:14 UTC
Labels: question, answered, reviewed, question-migrate
