### ISSUE TITLE
fastapi return null when return value is a long integer

### ISSUE THREAD

**Issue by mb19900210** [tiangolo/fastapi#2349] opened 2020-11-12 22:52 UTC
I am implementing a web app to print fibnocci series for any n number provided by the user.
In router part, I am able to see complete number, but when it comes to fastapi service, it fails to display larger number.

I am using ResponseModel as int and router looks like below:

    @router.get("/Fibonacci", response_model = int)
     def get_fibonacci(number: int) -> int:
         fib = fibonacci(number)
         return fib    
        // when I try to print fib, I could see long integer on my terminal, but on fastapi service, I see result as null.
       // where as it perfectly prints when value is upto: 927372692193079000000 (i.e.., fibnocci value of number: 102)

    fibnocci() returns int

Example value that I want to print(fibnocci value of 2000): 4224696333392304878706725602341482782579852840250681098010280137314308584370130707224123599639141511088446087538909603607640194711643596029271983312598737326253555802606991585915229492453904998722256795316982874482472992263901833716778060607011615497886719879858311468870876264597369086722884023654422295243347964480139515349562972087652656069529806499841977448720155612802665404554171717881930324025204312082516817125

Could someone suggest what could be the best way to display result as it is from the functionality ?
should I need to do any changes in ResponseModel ? or ?

**Comment by ycd** [comment] 2020-11-12 23:12
This is probably related to OpenAPI, it should be working when you send a cURL to it.

Try it yourself.

```curl
curl http://127.0.0.1:8000/Fibonacci
```

**Comment by mb19900210** [comment] 2020-11-13 10:30
> This is probably related to OpenAPI, it should be working when you send a cURL to it.
> 
> Try it yourself.
> 
> ```
> curl http://127.0.0.1:8000/Fibonacci
> ```

Is there a way to fix it ?

**Comment by Gascognya** [comment] 2020-11-13 11:27
The response message is correct。but problems start at 79。
It's the bug about OpenAPI Page(may be JS)
The frontend received 14472334024676221(fib 79) but display 14472334024676220

**Comment by ycd** [comment] 2021-02-09 00:46
> Is there a way to fix it ?

@mb19900210  It is not a bug, it is a limitation, fibonacci 2000 is too big that even JavaScript's BigInt can't handle it. Your code should work without an issue, you are only limited on Swagger.

**Comment by tiangolo** [comment] 2022-11-11 10:14
Thanks for the help here @ycd and @Gascognya ! 👏  🙇 

If that answers your question, then you can close this issue @mb19900210  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Closed** 2022-11-23 00:15 UTC
Labels: question, answered
