### ISSUE TITLE
`Request` provided as argument can be different from actual one

### ISSUE THREAD

**Issue by NickVeld** [tiangolo/fastapi#5460] opened 2022-10-05 18:08 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import fastapi
import fastapi.exception_handlers
import fastapi.testclient
import starlette.exceptions


app = fastapi.FastAPI(root_path="/api", title="Custom root path problem")
router = fastapi.APIRouter(prefix="/api")


@app.exception_handler(starlette.exceptions.HTTPException)
async def http_handler(request: fastapi.Request, exception: fastapi.HTTPException):
    print("HTTP error: ", exception.detail, "; URL in the request object:", request.url)
    response = await fastapi.exception_handlers.http_exception_handler(request, exception)
    return response


@app.exception_handler(Exception)
async def exception_handler(request: fastapi.Request, exception: Exception):
    print("Exception", exception, "; URL in the request object:", request.url)
    return fastapi.responses.PlainTextResponse(str(exception), status_code=500)


@router.get("/abc")
def abc_handler():
    raise Exception("Error in ABC")


@router.get("/xyz")
def xyz_handler(request: fastapi.Request):
    print("URL in the request-as-argument:", request.url)
    return "XYZ"


app.include_router(router)


if __name__ == "__main__":
    client = fastapi.testclient.TestClient(app)
    print("Test 1: request-as-argument vs response.request")

    url = "/api/xyz"
    response = client.get(url)
    print("URL in response.request:", response.request.url)

    print("Test 2: expected/not expected errors")

    print("Test 2.1:")
    url = "/abc"
    print("Requesting", url, "; NotFound is expected because the url is wrong")
    try:
        client.get(url)
    except Exception:
        print("Exception is caught")

    print("Test 2.1:")
    url = "/api/abc"
    print("Requesting", url, "; Exception is expected because the url is right")
    try:
        client.get(url)
    except Exception:
        print("Exception is caught")
```

### Description

The output of the example code:
```
Test 1: request-as-argument vs response.request
URL in the request-as-argument: http://testserver/api/api/xyz
URL in response.request: http://testserver/api/xyz
Test 2: expected/not expected errors
Test 2.1:
Requesting /abc ; NotFound is expected because the url is wrong
HTTP error:  Not Found ; URL in the request object: http://testserver/api/abc
Test 2.1:
Requesting /api/abc ; Exception is expected because the url is right
Exception Error in ABC ; URL in the request object: http://testserver/api/api/abc
Exception is caught
```

The output of the first test shows that the URL in the `Request` object that provided to the handler is different in comparison with the request provided in the response object (and the actual request I see in https://github.com/psf/requests/blob/fa1b0a367abc8488542f7ce7c02a3614ad8aa09d/requests/sessions.py#L645 ).

The second test shows the behavior of the server for the different requests and the URL the handlers sees in the direct `Request` object.

### Wanted Solution

In such case the best behavior is to have the identical request objects everywhere for such cases. If it is not possible it is will be better if they looks like identical in every case because it is expected to receive the actual request as an argument but not reconstructed one.

Maybe the problem with Starlette but I do not thinks so since the specific app configuration shows the problem.

If a repository maintainer agree that the described behavior is a problem than I can try to find a possible solution. I do not believe that it is easy so that's why I want to discuss the issue first.)

### Wanted Code

```python
Not relevant for now.
```

### Alternatives

Not relevant (for now?).

### Operating System

Windows

### Operating System Details

I believe that the OS is not important here.

### FastAPI Version

0.85.0

### Python Version

3.8.13

### Additional Context

I believe that the issue can be related to https://github.com/tiangolo/fastapi/issues/5344

**Comment by JarroVGIT** [comment] 2022-10-05 18:29
The request that is returned as part of the `Response` is not from FastAPI nor Starlette; it's from the `requests` model. The `Request` model as argument in your path endpoint function is from FastAPI (inherited from Starlette). They do not represent the same object and so they will not be the same object.  I've never dug too deep into the `TestClient` to be fair, but I would imagine it alters the behaviour of the `requests` package (note that this package is replaced by `httpx` in 0.21 of Starlette, and FastAPI is currently on 0.20.4).

Note that your application code does see the correct URLs from the parameter `Request` object; it's more of a `TestClient` implementation than anything else I'd say, and I don't think using the returned `request` object from the response is documented (or encouraged) behaviour.

**Comment by NickVeld** [comment] 2022-10-05 18:58
> it's from the requests model

Yes, I know but the question is how `Request` provided as an argument is created.

> They do not represent the same object and so they will not be the same object.
> I don't think using the returned request object from the response is documented (or encouraged) behaviour

But `request` attribute is a public one so it is allowed to read (or to be returned as an argument).

> this package is replaced by httpx in 0.21 of Starlette, and FastAPI is currently on 0.20.4

Yeah, it makes the issue solution is untimely now.

> Note that your application code does see the correct URLs from the parameter Request object
So do you believe that the right URL of abc_handler is `/api/api/abc` not `/api/abc`?

**Comment by JarroVGIT** [comment] 2022-10-05 19:12
> Yes, I know but the question is how `Request` provided as an argument is created.

That is basically a wrapper around the `scope` that is expected from a ASGI server like Starlette to handle. Uvicorn calls Starlette with 3 arguments; `scope`, `receive`, `send` where `scope` is a dictionary following the standard as [described here](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope). The `Request` object of Starlette is just a nice-to-have, and FastAPI injects it when you have a param of type `Request` declared in your path operation function. 

> But request attribute is a public one so it is allowed to read (or to be returned as an argument).

Yes sorry I've should've been clearer; no guarantees in the Starlette/FastAPI documentation is made on that attribute, and it isn't a Starlette/FastAPI object type. 

> So do you believe that the right URL of abc_handler is /api/api/abc not /api/abc?

Definitely yes. The first /api is from the root path that you've set on the application level. The second /api is from the router (which you gave a prefix of `/api`). The last part is just your endpoint that you've declared in your router. So, combining everything that would lead to root_path/prefix/endpoint = api/api/abc.

**Comment by NickVeld** [comment] 2022-10-06 05:01
By the way,

```
import fastapi
import fastapi.testclient


app = fastapi.FastAPI(root_path="/api", title="Custom root path problem")
router = fastapi.APIRouter()


@router.get("/xyz")
def xyz_handler(request: fastapi.Request):
    print("URL in the request-as-argument:", request.url)
    return "XYZ"


app.include_router(router)


if __name__ == "__main__":
    client = fastapi.testclient.TestClient(app)
    print("Test 1: request-as-argument vs response.request")

    url = "/xyz"
    response = client.get(url)
    print("URL in response.request:", response.request.url)
```

shows

```
Test 1: request-as-argument vs response.request
URL in the request-as-argument: http://testserver/api/xyz
URL in response.request: http://testserver/xyz
```

On the other hand:
```
import fastapi
import fastapi.testclient


app = fastapi.FastAPI(title="Custom root path problem")
router = fastapi.APIRouter(prefix="/api")


@router.get("/xyz")
def xyz_handler(request: fastapi.Request):
    print("URL in the request-as-argument:", request.url)
    return "XYZ"


app.include_router(router)


if __name__ == "__main__":
    client = fastapi.testclient.TestClient(app)
    print("Test 1: request-as-argument vs response.request")

    url = "/api/xyz"
    response = client.get(url)
    print("URL in response.request:", response.request.url)
```

shows

```
Test 1: request-as-argument vs response.request
URL in the request-as-argument: http://testserver/api/xyz
URL in response.request: http://testserver/api/xyz
```

So the problem is somewhere between `TestClient and `root_path`

**Comment by JarroVGIT** [comment] 2022-10-06 05:33
If you use `root_path` **or** `prefix` with the same values, then FastAPI will construct identical URLs in the `Request` object-as-parameter. 

The problem is not with root_path, the problem is with how `requests` package is used by `TestClient`. And to be fair, I would argue this is still correct as `root_path` is meant to make FastAPI (Starlette) believe that there is a default prefix to all routes. It is used in cases where there is a reverse proxy, and will let FastAPI know that normally, people will visit an URL with root_path in it but that a reverse proxy is stripping that. So what comes into FastAPI is actually without a root_path. Now, you are using a TestClient and not a reverse proxy, so the end result (the actual URL that hits your FastAPI application) will be the same.

**Comment by tiangolo** [comment] 2022-11-11 17:36
Thanks for the help here @JarroVGIT ! 👏  🙇 

If that solves the original problem, then you can close this issue @NickVeld  ✔️

Otherwise, please read carefully the docs about `root_path`: https://fastapi.tiangolo.com/advanced/behind-a-proxy/

**Closed** 2023-02-27 20:38 UTC
Labels: question, answered, reviewed, question-migrate
