### ISSUE TITLE
Delayed request body

### ISSUE THREAD

**Issue by ravi160822** [tiangolo/fastapi#5528] opened 2022-10-20 23:47 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
an update method
```

### Description

[
[Screen Recording 2022-10-21 at 4.49.03 AM.zip](https://github.com/tiangolo/fastapi/files/9834602/Screen.Recording.2022-10-21.at.4.49.03.AM.zip)
](url)

### Operating System

macOS

### FastAPI Version

0.85

### Python Version

3.10.7

**Comment by JarroVGIT** [comment] 2022-10-21 06:14
Please provide any detail. This is just a screen grab of a (small) part of SwaggerUI, I have no idea what the issue is or what you are trying to achieve. You provided no code whatsoever.

**Comment by ravi160822** [comment] 2022-10-21 16:21
I update the rank, but it gets displayed late, it gets displayed only after I click in the swagger ui.

**Comment by JarroVGIT** [comment] 2022-10-21 18:31
Because only when you click the button, you make a new request with new parameters to your FastAPI app.

**Comment by tiangolo** [comment] 2022-10-21 20:48
Thanks for the help here @JarroVGIT ! 🙇

I can't see the attachment right now, but if it's not related to FastAPI (as there's no FastAPI example code) then it would indeed not be related to FastAPI and it would need to be handled somewhere else.

If that's the case, then yep, you could close this issue and create one in the corresponding project. ☕

**Closed** 2023-02-27 20:37 UTC
Labels: question, answered, question-migrate
