### ISSUE TITLE
[DOCS] Add documentation on how to define a generic route

### ISSUE THREAD

**Issue by pydo** [tiangolo/fastapi#913] opened 2020-01-24 00:48 UTC
There isn't any documentation https://fastapi.tiangolo.com/ on how to define a generic route.

I think some  API documentation or an example of how to use `FastAPI.api_route()` would be useful

Related tickets: https://github.com/tiangolo/fastapi/issues/912 https://github.com/tiangolo/fastapi/issues/819

**Comment by tiangolo** [comment] 2020-02-13 20:58
Hmm, the problem is that it is not recommended. If you use that, you lose all the benefits of the data types. Data validation, serialization, docs, etc.

It would be mainly to allow people that want to migrate from Starlette or similar. But it is not recommended (rather discouraged).

**Comment by pydo** [comment] 2020-02-15 14:47
> If you use that, you lose all the benefits of the data types. Data validation, serialization, docs, etc.

I hadn't thought about that :thinking: . I guess it does make sense to avoid using them.

Thanks for the clarification

**Comment by tiangolo** [comment] 2020-04-07 17:05
Great, thanks! May we close this issue?

**Closed** 2020-04-18 00:01 UTC
Labels: enhancement
